// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: service.proto

package shreddrconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	shreddr "github.com/alecsavvy/shreddr/server/api/shreddr"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ShreddrServiceName is the fully-qualified name of the ShreddrService service.
	ShreddrServiceName = "shreddr.ShreddrService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ShreddrServiceListEventsProcedure is the fully-qualified name of the ShreddrService's ListEvents
	// RPC.
	ShreddrServiceListEventsProcedure = "/shreddr.ShreddrService/ListEvents"
	// ShreddrServiceGetEventProcedure is the fully-qualified name of the ShreddrService's GetEvent RPC.
	ShreddrServiceGetEventProcedure = "/shreddr.ShreddrService/GetEvent"
	// ShreddrServiceCreateEventProcedure is the fully-qualified name of the ShreddrService's
	// CreateEvent RPC.
	ShreddrServiceCreateEventProcedure = "/shreddr.ShreddrService/CreateEvent"
	// ShreddrServiceListTicketsProcedure is the fully-qualified name of the ShreddrService's
	// ListTickets RPC.
	ShreddrServiceListTicketsProcedure = "/shreddr.ShreddrService/ListTickets"
	// ShreddrServiceGetTicketProcedure is the fully-qualified name of the ShreddrService's GetTicket
	// RPC.
	ShreddrServiceGetTicketProcedure = "/shreddr.ShreddrService/GetTicket"
	// ShreddrServiceCreateTicketProcedure is the fully-qualified name of the ShreddrService's
	// CreateTicket RPC.
	ShreddrServiceCreateTicketProcedure = "/shreddr.ShreddrService/CreateTicket"
	// ShreddrServiceRedeemTicketProcedure is the fully-qualified name of the ShreddrService's
	// RedeemTicket RPC.
	ShreddrServiceRedeemTicketProcedure = "/shreddr.ShreddrService/RedeemTicket"
	// ShreddrServiceVerifyTicketProcedure is the fully-qualified name of the ShreddrService's
	// VerifyTicket RPC.
	ShreddrServiceVerifyTicketProcedure = "/shreddr.ShreddrService/VerifyTicket"
	// ShreddrServiceGetUserProcedure is the fully-qualified name of the ShreddrService's GetUser RPC.
	ShreddrServiceGetUserProcedure = "/shreddr.ShreddrService/GetUser"
	// ShreddrServiceGetUserByWalletProcedure is the fully-qualified name of the ShreddrService's
	// GetUserByWallet RPC.
	ShreddrServiceGetUserByWalletProcedure = "/shreddr.ShreddrService/GetUserByWallet"
	// ShreddrServiceCreateUserProcedure is the fully-qualified name of the ShreddrService's CreateUser
	// RPC.
	ShreddrServiceCreateUserProcedure = "/shreddr.ShreddrService/CreateUser"
	// ShreddrServiceCreatePurchaseProcedure is the fully-qualified name of the ShreddrService's
	// CreatePurchase RPC.
	ShreddrServiceCreatePurchaseProcedure = "/shreddr.ShreddrService/CreatePurchase"
	// ShreddrServiceGetPurchaseProcedure is the fully-qualified name of the ShreddrService's
	// GetPurchase RPC.
	ShreddrServiceGetPurchaseProcedure = "/shreddr.ShreddrService/GetPurchase"
	// ShreddrServiceUpdatePurchaseStatusProcedure is the fully-qualified name of the ShreddrService's
	// UpdatePurchaseStatus RPC.
	ShreddrServiceUpdatePurchaseStatusProcedure = "/shreddr.ShreddrService/UpdatePurchaseStatus"
	// ShreddrServiceListPurchasesProcedure is the fully-qualified name of the ShreddrService's
	// ListPurchases RPC.
	ShreddrServiceListPurchasesProcedure = "/shreddr.ShreddrService/ListPurchases"
)

// ShreddrServiceClient is a client for the shreddr.ShreddrService service.
type ShreddrServiceClient interface {
	// Events
	ListEvents(context.Context, *connect.Request[shreddr.ListEventsRequest]) (*connect.Response[shreddr.ListEventsResponse], error)
	GetEvent(context.Context, *connect.Request[shreddr.GetEventRequest]) (*connect.Response[shreddr.GetEventResponse], error)
	CreateEvent(context.Context, *connect.Request[shreddr.CreateEventRequest]) (*connect.Response[shreddr.CreateEventResponse], error)
	// Tickets
	ListTickets(context.Context, *connect.Request[shreddr.ListTicketsRequest]) (*connect.Response[shreddr.ListTicketsResponse], error)
	GetTicket(context.Context, *connect.Request[shreddr.GetTicketRequest]) (*connect.Response[shreddr.GetTicketResponse], error)
	CreateTicket(context.Context, *connect.Request[shreddr.CreateTicketRequest]) (*connect.Response[shreddr.CreateTicketResponse], error)
	RedeemTicket(context.Context, *connect.Request[shreddr.RedeemTicketRequest]) (*connect.Response[shreddr.RedeemTicketResponse], error)
	VerifyTicket(context.Context, *connect.Request[shreddr.VerifyTicketRequest]) (*connect.Response[shreddr.VerifyTicketResponse], error)
	// Users
	GetUser(context.Context, *connect.Request[shreddr.GetUserRequest]) (*connect.Response[shreddr.GetUserResponse], error)
	GetUserByWallet(context.Context, *connect.Request[shreddr.GetUserByWalletRequest]) (*connect.Response[shreddr.GetUserByWalletResponse], error)
	CreateUser(context.Context, *connect.Request[shreddr.CreateUserRequest]) (*connect.Response[shreddr.CreateUserResponse], error)
	// Purchases
	CreatePurchase(context.Context, *connect.Request[shreddr.CreatePurchaseRequest]) (*connect.Response[shreddr.CreatePurchaseResponse], error)
	GetPurchase(context.Context, *connect.Request[shreddr.GetPurchaseRequest]) (*connect.Response[shreddr.GetPurchaseResponse], error)
	UpdatePurchaseStatus(context.Context, *connect.Request[shreddr.UpdatePurchaseStatusRequest]) (*connect.Response[shreddr.UpdatePurchaseStatusResponse], error)
	ListPurchases(context.Context, *connect.Request[shreddr.ListPurchasesRequest]) (*connect.Response[shreddr.ListPurchasesResponse], error)
}

// NewShreddrServiceClient constructs a client for the shreddr.ShreddrService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewShreddrServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ShreddrServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	shreddrServiceMethods := shreddr.File_service_proto.Services().ByName("ShreddrService").Methods()
	return &shreddrServiceClient{
		listEvents: connect.NewClient[shreddr.ListEventsRequest, shreddr.ListEventsResponse](
			httpClient,
			baseURL+ShreddrServiceListEventsProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		getEvent: connect.NewClient[shreddr.GetEventRequest, shreddr.GetEventResponse](
			httpClient,
			baseURL+ShreddrServiceGetEventProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("GetEvent")),
			connect.WithClientOptions(opts...),
		),
		createEvent: connect.NewClient[shreddr.CreateEventRequest, shreddr.CreateEventResponse](
			httpClient,
			baseURL+ShreddrServiceCreateEventProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("CreateEvent")),
			connect.WithClientOptions(opts...),
		),
		listTickets: connect.NewClient[shreddr.ListTicketsRequest, shreddr.ListTicketsResponse](
			httpClient,
			baseURL+ShreddrServiceListTicketsProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("ListTickets")),
			connect.WithClientOptions(opts...),
		),
		getTicket: connect.NewClient[shreddr.GetTicketRequest, shreddr.GetTicketResponse](
			httpClient,
			baseURL+ShreddrServiceGetTicketProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("GetTicket")),
			connect.WithClientOptions(opts...),
		),
		createTicket: connect.NewClient[shreddr.CreateTicketRequest, shreddr.CreateTicketResponse](
			httpClient,
			baseURL+ShreddrServiceCreateTicketProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("CreateTicket")),
			connect.WithClientOptions(opts...),
		),
		redeemTicket: connect.NewClient[shreddr.RedeemTicketRequest, shreddr.RedeemTicketResponse](
			httpClient,
			baseURL+ShreddrServiceRedeemTicketProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("RedeemTicket")),
			connect.WithClientOptions(opts...),
		),
		verifyTicket: connect.NewClient[shreddr.VerifyTicketRequest, shreddr.VerifyTicketResponse](
			httpClient,
			baseURL+ShreddrServiceVerifyTicketProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("VerifyTicket")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[shreddr.GetUserRequest, shreddr.GetUserResponse](
			httpClient,
			baseURL+ShreddrServiceGetUserProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		getUserByWallet: connect.NewClient[shreddr.GetUserByWalletRequest, shreddr.GetUserByWalletResponse](
			httpClient,
			baseURL+ShreddrServiceGetUserByWalletProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("GetUserByWallet")),
			connect.WithClientOptions(opts...),
		),
		createUser: connect.NewClient[shreddr.CreateUserRequest, shreddr.CreateUserResponse](
			httpClient,
			baseURL+ShreddrServiceCreateUserProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		createPurchase: connect.NewClient[shreddr.CreatePurchaseRequest, shreddr.CreatePurchaseResponse](
			httpClient,
			baseURL+ShreddrServiceCreatePurchaseProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("CreatePurchase")),
			connect.WithClientOptions(opts...),
		),
		getPurchase: connect.NewClient[shreddr.GetPurchaseRequest, shreddr.GetPurchaseResponse](
			httpClient,
			baseURL+ShreddrServiceGetPurchaseProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("GetPurchase")),
			connect.WithClientOptions(opts...),
		),
		updatePurchaseStatus: connect.NewClient[shreddr.UpdatePurchaseStatusRequest, shreddr.UpdatePurchaseStatusResponse](
			httpClient,
			baseURL+ShreddrServiceUpdatePurchaseStatusProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("UpdatePurchaseStatus")),
			connect.WithClientOptions(opts...),
		),
		listPurchases: connect.NewClient[shreddr.ListPurchasesRequest, shreddr.ListPurchasesResponse](
			httpClient,
			baseURL+ShreddrServiceListPurchasesProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("ListPurchases")),
			connect.WithClientOptions(opts...),
		),
	}
}

// shreddrServiceClient implements ShreddrServiceClient.
type shreddrServiceClient struct {
	listEvents           *connect.Client[shreddr.ListEventsRequest, shreddr.ListEventsResponse]
	getEvent             *connect.Client[shreddr.GetEventRequest, shreddr.GetEventResponse]
	createEvent          *connect.Client[shreddr.CreateEventRequest, shreddr.CreateEventResponse]
	listTickets          *connect.Client[shreddr.ListTicketsRequest, shreddr.ListTicketsResponse]
	getTicket            *connect.Client[shreddr.GetTicketRequest, shreddr.GetTicketResponse]
	createTicket         *connect.Client[shreddr.CreateTicketRequest, shreddr.CreateTicketResponse]
	redeemTicket         *connect.Client[shreddr.RedeemTicketRequest, shreddr.RedeemTicketResponse]
	verifyTicket         *connect.Client[shreddr.VerifyTicketRequest, shreddr.VerifyTicketResponse]
	getUser              *connect.Client[shreddr.GetUserRequest, shreddr.GetUserResponse]
	getUserByWallet      *connect.Client[shreddr.GetUserByWalletRequest, shreddr.GetUserByWalletResponse]
	createUser           *connect.Client[shreddr.CreateUserRequest, shreddr.CreateUserResponse]
	createPurchase       *connect.Client[shreddr.CreatePurchaseRequest, shreddr.CreatePurchaseResponse]
	getPurchase          *connect.Client[shreddr.GetPurchaseRequest, shreddr.GetPurchaseResponse]
	updatePurchaseStatus *connect.Client[shreddr.UpdatePurchaseStatusRequest, shreddr.UpdatePurchaseStatusResponse]
	listPurchases        *connect.Client[shreddr.ListPurchasesRequest, shreddr.ListPurchasesResponse]
}

// ListEvents calls shreddr.ShreddrService.ListEvents.
func (c *shreddrServiceClient) ListEvents(ctx context.Context, req *connect.Request[shreddr.ListEventsRequest]) (*connect.Response[shreddr.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// GetEvent calls shreddr.ShreddrService.GetEvent.
func (c *shreddrServiceClient) GetEvent(ctx context.Context, req *connect.Request[shreddr.GetEventRequest]) (*connect.Response[shreddr.GetEventResponse], error) {
	return c.getEvent.CallUnary(ctx, req)
}

// CreateEvent calls shreddr.ShreddrService.CreateEvent.
func (c *shreddrServiceClient) CreateEvent(ctx context.Context, req *connect.Request[shreddr.CreateEventRequest]) (*connect.Response[shreddr.CreateEventResponse], error) {
	return c.createEvent.CallUnary(ctx, req)
}

// ListTickets calls shreddr.ShreddrService.ListTickets.
func (c *shreddrServiceClient) ListTickets(ctx context.Context, req *connect.Request[shreddr.ListTicketsRequest]) (*connect.Response[shreddr.ListTicketsResponse], error) {
	return c.listTickets.CallUnary(ctx, req)
}

// GetTicket calls shreddr.ShreddrService.GetTicket.
func (c *shreddrServiceClient) GetTicket(ctx context.Context, req *connect.Request[shreddr.GetTicketRequest]) (*connect.Response[shreddr.GetTicketResponse], error) {
	return c.getTicket.CallUnary(ctx, req)
}

// CreateTicket calls shreddr.ShreddrService.CreateTicket.
func (c *shreddrServiceClient) CreateTicket(ctx context.Context, req *connect.Request[shreddr.CreateTicketRequest]) (*connect.Response[shreddr.CreateTicketResponse], error) {
	return c.createTicket.CallUnary(ctx, req)
}

// RedeemTicket calls shreddr.ShreddrService.RedeemTicket.
func (c *shreddrServiceClient) RedeemTicket(ctx context.Context, req *connect.Request[shreddr.RedeemTicketRequest]) (*connect.Response[shreddr.RedeemTicketResponse], error) {
	return c.redeemTicket.CallUnary(ctx, req)
}

// VerifyTicket calls shreddr.ShreddrService.VerifyTicket.
func (c *shreddrServiceClient) VerifyTicket(ctx context.Context, req *connect.Request[shreddr.VerifyTicketRequest]) (*connect.Response[shreddr.VerifyTicketResponse], error) {
	return c.verifyTicket.CallUnary(ctx, req)
}

// GetUser calls shreddr.ShreddrService.GetUser.
func (c *shreddrServiceClient) GetUser(ctx context.Context, req *connect.Request[shreddr.GetUserRequest]) (*connect.Response[shreddr.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// GetUserByWallet calls shreddr.ShreddrService.GetUserByWallet.
func (c *shreddrServiceClient) GetUserByWallet(ctx context.Context, req *connect.Request[shreddr.GetUserByWalletRequest]) (*connect.Response[shreddr.GetUserByWalletResponse], error) {
	return c.getUserByWallet.CallUnary(ctx, req)
}

// CreateUser calls shreddr.ShreddrService.CreateUser.
func (c *shreddrServiceClient) CreateUser(ctx context.Context, req *connect.Request[shreddr.CreateUserRequest]) (*connect.Response[shreddr.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// CreatePurchase calls shreddr.ShreddrService.CreatePurchase.
func (c *shreddrServiceClient) CreatePurchase(ctx context.Context, req *connect.Request[shreddr.CreatePurchaseRequest]) (*connect.Response[shreddr.CreatePurchaseResponse], error) {
	return c.createPurchase.CallUnary(ctx, req)
}

// GetPurchase calls shreddr.ShreddrService.GetPurchase.
func (c *shreddrServiceClient) GetPurchase(ctx context.Context, req *connect.Request[shreddr.GetPurchaseRequest]) (*connect.Response[shreddr.GetPurchaseResponse], error) {
	return c.getPurchase.CallUnary(ctx, req)
}

// UpdatePurchaseStatus calls shreddr.ShreddrService.UpdatePurchaseStatus.
func (c *shreddrServiceClient) UpdatePurchaseStatus(ctx context.Context, req *connect.Request[shreddr.UpdatePurchaseStatusRequest]) (*connect.Response[shreddr.UpdatePurchaseStatusResponse], error) {
	return c.updatePurchaseStatus.CallUnary(ctx, req)
}

// ListPurchases calls shreddr.ShreddrService.ListPurchases.
func (c *shreddrServiceClient) ListPurchases(ctx context.Context, req *connect.Request[shreddr.ListPurchasesRequest]) (*connect.Response[shreddr.ListPurchasesResponse], error) {
	return c.listPurchases.CallUnary(ctx, req)
}

// ShreddrServiceHandler is an implementation of the shreddr.ShreddrService service.
type ShreddrServiceHandler interface {
	// Events
	ListEvents(context.Context, *connect.Request[shreddr.ListEventsRequest]) (*connect.Response[shreddr.ListEventsResponse], error)
	GetEvent(context.Context, *connect.Request[shreddr.GetEventRequest]) (*connect.Response[shreddr.GetEventResponse], error)
	CreateEvent(context.Context, *connect.Request[shreddr.CreateEventRequest]) (*connect.Response[shreddr.CreateEventResponse], error)
	// Tickets
	ListTickets(context.Context, *connect.Request[shreddr.ListTicketsRequest]) (*connect.Response[shreddr.ListTicketsResponse], error)
	GetTicket(context.Context, *connect.Request[shreddr.GetTicketRequest]) (*connect.Response[shreddr.GetTicketResponse], error)
	CreateTicket(context.Context, *connect.Request[shreddr.CreateTicketRequest]) (*connect.Response[shreddr.CreateTicketResponse], error)
	RedeemTicket(context.Context, *connect.Request[shreddr.RedeemTicketRequest]) (*connect.Response[shreddr.RedeemTicketResponse], error)
	VerifyTicket(context.Context, *connect.Request[shreddr.VerifyTicketRequest]) (*connect.Response[shreddr.VerifyTicketResponse], error)
	// Users
	GetUser(context.Context, *connect.Request[shreddr.GetUserRequest]) (*connect.Response[shreddr.GetUserResponse], error)
	GetUserByWallet(context.Context, *connect.Request[shreddr.GetUserByWalletRequest]) (*connect.Response[shreddr.GetUserByWalletResponse], error)
	CreateUser(context.Context, *connect.Request[shreddr.CreateUserRequest]) (*connect.Response[shreddr.CreateUserResponse], error)
	// Purchases
	CreatePurchase(context.Context, *connect.Request[shreddr.CreatePurchaseRequest]) (*connect.Response[shreddr.CreatePurchaseResponse], error)
	GetPurchase(context.Context, *connect.Request[shreddr.GetPurchaseRequest]) (*connect.Response[shreddr.GetPurchaseResponse], error)
	UpdatePurchaseStatus(context.Context, *connect.Request[shreddr.UpdatePurchaseStatusRequest]) (*connect.Response[shreddr.UpdatePurchaseStatusResponse], error)
	ListPurchases(context.Context, *connect.Request[shreddr.ListPurchasesRequest]) (*connect.Response[shreddr.ListPurchasesResponse], error)
}

// NewShreddrServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewShreddrServiceHandler(svc ShreddrServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	shreddrServiceMethods := shreddr.File_service_proto.Services().ByName("ShreddrService").Methods()
	shreddrServiceListEventsHandler := connect.NewUnaryHandler(
		ShreddrServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(shreddrServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceGetEventHandler := connect.NewUnaryHandler(
		ShreddrServiceGetEventProcedure,
		svc.GetEvent,
		connect.WithSchema(shreddrServiceMethods.ByName("GetEvent")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceCreateEventHandler := connect.NewUnaryHandler(
		ShreddrServiceCreateEventProcedure,
		svc.CreateEvent,
		connect.WithSchema(shreddrServiceMethods.ByName("CreateEvent")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceListTicketsHandler := connect.NewUnaryHandler(
		ShreddrServiceListTicketsProcedure,
		svc.ListTickets,
		connect.WithSchema(shreddrServiceMethods.ByName("ListTickets")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceGetTicketHandler := connect.NewUnaryHandler(
		ShreddrServiceGetTicketProcedure,
		svc.GetTicket,
		connect.WithSchema(shreddrServiceMethods.ByName("GetTicket")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceCreateTicketHandler := connect.NewUnaryHandler(
		ShreddrServiceCreateTicketProcedure,
		svc.CreateTicket,
		connect.WithSchema(shreddrServiceMethods.ByName("CreateTicket")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceRedeemTicketHandler := connect.NewUnaryHandler(
		ShreddrServiceRedeemTicketProcedure,
		svc.RedeemTicket,
		connect.WithSchema(shreddrServiceMethods.ByName("RedeemTicket")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceVerifyTicketHandler := connect.NewUnaryHandler(
		ShreddrServiceVerifyTicketProcedure,
		svc.VerifyTicket,
		connect.WithSchema(shreddrServiceMethods.ByName("VerifyTicket")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceGetUserHandler := connect.NewUnaryHandler(
		ShreddrServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(shreddrServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceGetUserByWalletHandler := connect.NewUnaryHandler(
		ShreddrServiceGetUserByWalletProcedure,
		svc.GetUserByWallet,
		connect.WithSchema(shreddrServiceMethods.ByName("GetUserByWallet")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceCreateUserHandler := connect.NewUnaryHandler(
		ShreddrServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(shreddrServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceCreatePurchaseHandler := connect.NewUnaryHandler(
		ShreddrServiceCreatePurchaseProcedure,
		svc.CreatePurchase,
		connect.WithSchema(shreddrServiceMethods.ByName("CreatePurchase")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceGetPurchaseHandler := connect.NewUnaryHandler(
		ShreddrServiceGetPurchaseProcedure,
		svc.GetPurchase,
		connect.WithSchema(shreddrServiceMethods.ByName("GetPurchase")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceUpdatePurchaseStatusHandler := connect.NewUnaryHandler(
		ShreddrServiceUpdatePurchaseStatusProcedure,
		svc.UpdatePurchaseStatus,
		connect.WithSchema(shreddrServiceMethods.ByName("UpdatePurchaseStatus")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceListPurchasesHandler := connect.NewUnaryHandler(
		ShreddrServiceListPurchasesProcedure,
		svc.ListPurchases,
		connect.WithSchema(shreddrServiceMethods.ByName("ListPurchases")),
		connect.WithHandlerOptions(opts...),
	)
	return "/shreddr.ShreddrService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ShreddrServiceListEventsProcedure:
			shreddrServiceListEventsHandler.ServeHTTP(w, r)
		case ShreddrServiceGetEventProcedure:
			shreddrServiceGetEventHandler.ServeHTTP(w, r)
		case ShreddrServiceCreateEventProcedure:
			shreddrServiceCreateEventHandler.ServeHTTP(w, r)
		case ShreddrServiceListTicketsProcedure:
			shreddrServiceListTicketsHandler.ServeHTTP(w, r)
		case ShreddrServiceGetTicketProcedure:
			shreddrServiceGetTicketHandler.ServeHTTP(w, r)
		case ShreddrServiceCreateTicketProcedure:
			shreddrServiceCreateTicketHandler.ServeHTTP(w, r)
		case ShreddrServiceRedeemTicketProcedure:
			shreddrServiceRedeemTicketHandler.ServeHTTP(w, r)
		case ShreddrServiceVerifyTicketProcedure:
			shreddrServiceVerifyTicketHandler.ServeHTTP(w, r)
		case ShreddrServiceGetUserProcedure:
			shreddrServiceGetUserHandler.ServeHTTP(w, r)
		case ShreddrServiceGetUserByWalletProcedure:
			shreddrServiceGetUserByWalletHandler.ServeHTTP(w, r)
		case ShreddrServiceCreateUserProcedure:
			shreddrServiceCreateUserHandler.ServeHTTP(w, r)
		case ShreddrServiceCreatePurchaseProcedure:
			shreddrServiceCreatePurchaseHandler.ServeHTTP(w, r)
		case ShreddrServiceGetPurchaseProcedure:
			shreddrServiceGetPurchaseHandler.ServeHTTP(w, r)
		case ShreddrServiceUpdatePurchaseStatusProcedure:
			shreddrServiceUpdatePurchaseStatusHandler.ServeHTTP(w, r)
		case ShreddrServiceListPurchasesProcedure:
			shreddrServiceListPurchasesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedShreddrServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedShreddrServiceHandler struct{}

func (UnimplementedShreddrServiceHandler) ListEvents(context.Context, *connect.Request[shreddr.ListEventsRequest]) (*connect.Response[shreddr.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.ListEvents is not implemented"))
}

func (UnimplementedShreddrServiceHandler) GetEvent(context.Context, *connect.Request[shreddr.GetEventRequest]) (*connect.Response[shreddr.GetEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.GetEvent is not implemented"))
}

func (UnimplementedShreddrServiceHandler) CreateEvent(context.Context, *connect.Request[shreddr.CreateEventRequest]) (*connect.Response[shreddr.CreateEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.CreateEvent is not implemented"))
}

func (UnimplementedShreddrServiceHandler) ListTickets(context.Context, *connect.Request[shreddr.ListTicketsRequest]) (*connect.Response[shreddr.ListTicketsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.ListTickets is not implemented"))
}

func (UnimplementedShreddrServiceHandler) GetTicket(context.Context, *connect.Request[shreddr.GetTicketRequest]) (*connect.Response[shreddr.GetTicketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.GetTicket is not implemented"))
}

func (UnimplementedShreddrServiceHandler) CreateTicket(context.Context, *connect.Request[shreddr.CreateTicketRequest]) (*connect.Response[shreddr.CreateTicketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.CreateTicket is not implemented"))
}

func (UnimplementedShreddrServiceHandler) RedeemTicket(context.Context, *connect.Request[shreddr.RedeemTicketRequest]) (*connect.Response[shreddr.RedeemTicketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.RedeemTicket is not implemented"))
}

func (UnimplementedShreddrServiceHandler) VerifyTicket(context.Context, *connect.Request[shreddr.VerifyTicketRequest]) (*connect.Response[shreddr.VerifyTicketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.VerifyTicket is not implemented"))
}

func (UnimplementedShreddrServiceHandler) GetUser(context.Context, *connect.Request[shreddr.GetUserRequest]) (*connect.Response[shreddr.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.GetUser is not implemented"))
}

func (UnimplementedShreddrServiceHandler) GetUserByWallet(context.Context, *connect.Request[shreddr.GetUserByWalletRequest]) (*connect.Response[shreddr.GetUserByWalletResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.GetUserByWallet is not implemented"))
}

func (UnimplementedShreddrServiceHandler) CreateUser(context.Context, *connect.Request[shreddr.CreateUserRequest]) (*connect.Response[shreddr.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.CreateUser is not implemented"))
}

func (UnimplementedShreddrServiceHandler) CreatePurchase(context.Context, *connect.Request[shreddr.CreatePurchaseRequest]) (*connect.Response[shreddr.CreatePurchaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.CreatePurchase is not implemented"))
}

func (UnimplementedShreddrServiceHandler) GetPurchase(context.Context, *connect.Request[shreddr.GetPurchaseRequest]) (*connect.Response[shreddr.GetPurchaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.GetPurchase is not implemented"))
}

func (UnimplementedShreddrServiceHandler) UpdatePurchaseStatus(context.Context, *connect.Request[shreddr.UpdatePurchaseStatusRequest]) (*connect.Response[shreddr.UpdatePurchaseStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.UpdatePurchaseStatus is not implemented"))
}

func (UnimplementedShreddrServiceHandler) ListPurchases(context.Context, *connect.Request[shreddr.ListPurchasesRequest]) (*connect.Response[shreddr.ListPurchasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.ListPurchases is not implemented"))
}
