// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: events.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/alecsavvy/shreddr/server/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EventServiceName is the fully-qualified name of the EventService service.
	EventServiceName = "api.EventService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventServiceListEventsProcedure is the fully-qualified name of the EventService's ListEvents RPC.
	EventServiceListEventsProcedure = "/api.EventService/ListEvents"
	// EventServiceGetEventProcedure is the fully-qualified name of the EventService's GetEvent RPC.
	EventServiceGetEventProcedure = "/api.EventService/GetEvent"
	// EventServiceCreateEventProcedure is the fully-qualified name of the EventService's CreateEvent
	// RPC.
	EventServiceCreateEventProcedure = "/api.EventService/CreateEvent"
)

// EventServiceClient is a client for the api.EventService service.
type EventServiceClient interface {
	ListEvents(context.Context, *connect.Request[api.ListEventsRequest]) (*connect.Response[api.ListEventsResponse], error)
	GetEvent(context.Context, *connect.Request[api.GetEventRequest]) (*connect.Response[api.GetEventResponse], error)
	CreateEvent(context.Context, *connect.Request[api.CreateEventRequest]) (*connect.Response[api.CreateEventResponse], error)
}

// NewEventServiceClient constructs a client for the api.EventService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventServiceMethods := api.File_events_proto.Services().ByName("EventService").Methods()
	return &eventServiceClient{
		listEvents: connect.NewClient[api.ListEventsRequest, api.ListEventsResponse](
			httpClient,
			baseURL+EventServiceListEventsProcedure,
			connect.WithSchema(eventServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		getEvent: connect.NewClient[api.GetEventRequest, api.GetEventResponse](
			httpClient,
			baseURL+EventServiceGetEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("GetEvent")),
			connect.WithClientOptions(opts...),
		),
		createEvent: connect.NewClient[api.CreateEventRequest, api.CreateEventResponse](
			httpClient,
			baseURL+EventServiceCreateEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("CreateEvent")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventServiceClient implements EventServiceClient.
type eventServiceClient struct {
	listEvents  *connect.Client[api.ListEventsRequest, api.ListEventsResponse]
	getEvent    *connect.Client[api.GetEventRequest, api.GetEventResponse]
	createEvent *connect.Client[api.CreateEventRequest, api.CreateEventResponse]
}

// ListEvents calls api.EventService.ListEvents.
func (c *eventServiceClient) ListEvents(ctx context.Context, req *connect.Request[api.ListEventsRequest]) (*connect.Response[api.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// GetEvent calls api.EventService.GetEvent.
func (c *eventServiceClient) GetEvent(ctx context.Context, req *connect.Request[api.GetEventRequest]) (*connect.Response[api.GetEventResponse], error) {
	return c.getEvent.CallUnary(ctx, req)
}

// CreateEvent calls api.EventService.CreateEvent.
func (c *eventServiceClient) CreateEvent(ctx context.Context, req *connect.Request[api.CreateEventRequest]) (*connect.Response[api.CreateEventResponse], error) {
	return c.createEvent.CallUnary(ctx, req)
}

// EventServiceHandler is an implementation of the api.EventService service.
type EventServiceHandler interface {
	ListEvents(context.Context, *connect.Request[api.ListEventsRequest]) (*connect.Response[api.ListEventsResponse], error)
	GetEvent(context.Context, *connect.Request[api.GetEventRequest]) (*connect.Response[api.GetEventResponse], error)
	CreateEvent(context.Context, *connect.Request[api.CreateEventRequest]) (*connect.Response[api.CreateEventResponse], error)
}

// NewEventServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventServiceHandler(svc EventServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventServiceMethods := api.File_events_proto.Services().ByName("EventService").Methods()
	eventServiceListEventsHandler := connect.NewUnaryHandler(
		EventServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(eventServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceGetEventHandler := connect.NewUnaryHandler(
		EventServiceGetEventProcedure,
		svc.GetEvent,
		connect.WithSchema(eventServiceMethods.ByName("GetEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceCreateEventHandler := connect.NewUnaryHandler(
		EventServiceCreateEventProcedure,
		svc.CreateEvent,
		connect.WithSchema(eventServiceMethods.ByName("CreateEvent")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.EventService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventServiceListEventsProcedure:
			eventServiceListEventsHandler.ServeHTTP(w, r)
		case EventServiceGetEventProcedure:
			eventServiceGetEventHandler.ServeHTTP(w, r)
		case EventServiceCreateEventProcedure:
			eventServiceCreateEventHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventServiceHandler struct{}

func (UnimplementedEventServiceHandler) ListEvents(context.Context, *connect.Request[api.ListEventsRequest]) (*connect.Response[api.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.EventService.ListEvents is not implemented"))
}

func (UnimplementedEventServiceHandler) GetEvent(context.Context, *connect.Request[api.GetEventRequest]) (*connect.Response[api.GetEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.EventService.GetEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) CreateEvent(context.Context, *connect.Request[api.CreateEventRequest]) (*connect.Response[api.CreateEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.EventService.CreateEvent is not implemented"))
}
