// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: service.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/alecsavvy/shreddr/server/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ShreddrServiceName is the fully-qualified name of the ShreddrService service.
	ShreddrServiceName = "shreddr.ShreddrService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ShreddrServiceListEventsProcedure is the fully-qualified name of the ShreddrService's ListEvents
	// RPC.
	ShreddrServiceListEventsProcedure = "/shreddr.ShreddrService/ListEvents"
	// ShreddrServiceGetEventProcedure is the fully-qualified name of the ShreddrService's GetEvent RPC.
	ShreddrServiceGetEventProcedure = "/shreddr.ShreddrService/GetEvent"
	// ShreddrServiceCreateEventProcedure is the fully-qualified name of the ShreddrService's
	// CreateEvent RPC.
	ShreddrServiceCreateEventProcedure = "/shreddr.ShreddrService/CreateEvent"
	// ShreddrServiceGetUserByWalletProcedure is the fully-qualified name of the ShreddrService's
	// GetUserByWallet RPC.
	ShreddrServiceGetUserByWalletProcedure = "/shreddr.ShreddrService/GetUserByWallet"
	// ShreddrServiceCreateUserProcedure is the fully-qualified name of the ShreddrService's CreateUser
	// RPC.
	ShreddrServiceCreateUserProcedure = "/shreddr.ShreddrService/CreateUser"
)

// ShreddrServiceClient is a client for the shreddr.ShreddrService service.
type ShreddrServiceClient interface {
	// Events
	ListEvents(context.Context, *connect.Request[api.ListEventsRequest]) (*connect.Response[api.ListEventsResponse], error)
	GetEvent(context.Context, *connect.Request[api.GetEventRequest]) (*connect.Response[api.GetEventResponse], error)
	CreateEvent(context.Context, *connect.Request[api.CreateEventRequest]) (*connect.Response[api.CreateEventResponse], error)
	// Users
	GetUserByWallet(context.Context, *connect.Request[api.GetUserByWalletRequest]) (*connect.Response[api.GetUserByWalletResponse], error)
	CreateUser(context.Context, *connect.Request[api.CreateUserRequest]) (*connect.Response[api.CreateUserResponse], error)
}

// NewShreddrServiceClient constructs a client for the shreddr.ShreddrService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewShreddrServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ShreddrServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	shreddrServiceMethods := api.File_service_proto.Services().ByName("ShreddrService").Methods()
	return &shreddrServiceClient{
		listEvents: connect.NewClient[api.ListEventsRequest, api.ListEventsResponse](
			httpClient,
			baseURL+ShreddrServiceListEventsProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		getEvent: connect.NewClient[api.GetEventRequest, api.GetEventResponse](
			httpClient,
			baseURL+ShreddrServiceGetEventProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("GetEvent")),
			connect.WithClientOptions(opts...),
		),
		createEvent: connect.NewClient[api.CreateEventRequest, api.CreateEventResponse](
			httpClient,
			baseURL+ShreddrServiceCreateEventProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("CreateEvent")),
			connect.WithClientOptions(opts...),
		),
		getUserByWallet: connect.NewClient[api.GetUserByWalletRequest, api.GetUserByWalletResponse](
			httpClient,
			baseURL+ShreddrServiceGetUserByWalletProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("GetUserByWallet")),
			connect.WithClientOptions(opts...),
		),
		createUser: connect.NewClient[api.CreateUserRequest, api.CreateUserResponse](
			httpClient,
			baseURL+ShreddrServiceCreateUserProcedure,
			connect.WithSchema(shreddrServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// shreddrServiceClient implements ShreddrServiceClient.
type shreddrServiceClient struct {
	listEvents      *connect.Client[api.ListEventsRequest, api.ListEventsResponse]
	getEvent        *connect.Client[api.GetEventRequest, api.GetEventResponse]
	createEvent     *connect.Client[api.CreateEventRequest, api.CreateEventResponse]
	getUserByWallet *connect.Client[api.GetUserByWalletRequest, api.GetUserByWalletResponse]
	createUser      *connect.Client[api.CreateUserRequest, api.CreateUserResponse]
}

// ListEvents calls shreddr.ShreddrService.ListEvents.
func (c *shreddrServiceClient) ListEvents(ctx context.Context, req *connect.Request[api.ListEventsRequest]) (*connect.Response[api.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// GetEvent calls shreddr.ShreddrService.GetEvent.
func (c *shreddrServiceClient) GetEvent(ctx context.Context, req *connect.Request[api.GetEventRequest]) (*connect.Response[api.GetEventResponse], error) {
	return c.getEvent.CallUnary(ctx, req)
}

// CreateEvent calls shreddr.ShreddrService.CreateEvent.
func (c *shreddrServiceClient) CreateEvent(ctx context.Context, req *connect.Request[api.CreateEventRequest]) (*connect.Response[api.CreateEventResponse], error) {
	return c.createEvent.CallUnary(ctx, req)
}

// GetUserByWallet calls shreddr.ShreddrService.GetUserByWallet.
func (c *shreddrServiceClient) GetUserByWallet(ctx context.Context, req *connect.Request[api.GetUserByWalletRequest]) (*connect.Response[api.GetUserByWalletResponse], error) {
	return c.getUserByWallet.CallUnary(ctx, req)
}

// CreateUser calls shreddr.ShreddrService.CreateUser.
func (c *shreddrServiceClient) CreateUser(ctx context.Context, req *connect.Request[api.CreateUserRequest]) (*connect.Response[api.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// ShreddrServiceHandler is an implementation of the shreddr.ShreddrService service.
type ShreddrServiceHandler interface {
	// Events
	ListEvents(context.Context, *connect.Request[api.ListEventsRequest]) (*connect.Response[api.ListEventsResponse], error)
	GetEvent(context.Context, *connect.Request[api.GetEventRequest]) (*connect.Response[api.GetEventResponse], error)
	CreateEvent(context.Context, *connect.Request[api.CreateEventRequest]) (*connect.Response[api.CreateEventResponse], error)
	// Users
	GetUserByWallet(context.Context, *connect.Request[api.GetUserByWalletRequest]) (*connect.Response[api.GetUserByWalletResponse], error)
	CreateUser(context.Context, *connect.Request[api.CreateUserRequest]) (*connect.Response[api.CreateUserResponse], error)
}

// NewShreddrServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewShreddrServiceHandler(svc ShreddrServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	shreddrServiceMethods := api.File_service_proto.Services().ByName("ShreddrService").Methods()
	shreddrServiceListEventsHandler := connect.NewUnaryHandler(
		ShreddrServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(shreddrServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceGetEventHandler := connect.NewUnaryHandler(
		ShreddrServiceGetEventProcedure,
		svc.GetEvent,
		connect.WithSchema(shreddrServiceMethods.ByName("GetEvent")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceCreateEventHandler := connect.NewUnaryHandler(
		ShreddrServiceCreateEventProcedure,
		svc.CreateEvent,
		connect.WithSchema(shreddrServiceMethods.ByName("CreateEvent")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceGetUserByWalletHandler := connect.NewUnaryHandler(
		ShreddrServiceGetUserByWalletProcedure,
		svc.GetUserByWallet,
		connect.WithSchema(shreddrServiceMethods.ByName("GetUserByWallet")),
		connect.WithHandlerOptions(opts...),
	)
	shreddrServiceCreateUserHandler := connect.NewUnaryHandler(
		ShreddrServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(shreddrServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/shreddr.ShreddrService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ShreddrServiceListEventsProcedure:
			shreddrServiceListEventsHandler.ServeHTTP(w, r)
		case ShreddrServiceGetEventProcedure:
			shreddrServiceGetEventHandler.ServeHTTP(w, r)
		case ShreddrServiceCreateEventProcedure:
			shreddrServiceCreateEventHandler.ServeHTTP(w, r)
		case ShreddrServiceGetUserByWalletProcedure:
			shreddrServiceGetUserByWalletHandler.ServeHTTP(w, r)
		case ShreddrServiceCreateUserProcedure:
			shreddrServiceCreateUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedShreddrServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedShreddrServiceHandler struct{}

func (UnimplementedShreddrServiceHandler) ListEvents(context.Context, *connect.Request[api.ListEventsRequest]) (*connect.Response[api.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.ListEvents is not implemented"))
}

func (UnimplementedShreddrServiceHandler) GetEvent(context.Context, *connect.Request[api.GetEventRequest]) (*connect.Response[api.GetEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.GetEvent is not implemented"))
}

func (UnimplementedShreddrServiceHandler) CreateEvent(context.Context, *connect.Request[api.CreateEventRequest]) (*connect.Response[api.CreateEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.CreateEvent is not implemented"))
}

func (UnimplementedShreddrServiceHandler) GetUserByWallet(context.Context, *connect.Request[api.GetUserByWalletRequest]) (*connect.Response[api.GetUserByWalletResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.GetUserByWallet is not implemented"))
}

func (UnimplementedShreddrServiceHandler) CreateUser(context.Context, *connect.Request[api.CreateUserRequest]) (*connect.Response[api.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shreddr.ShreddrService.CreateUser is not implemented"))
}
