// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tickets.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/alecsavvy/shreddr/server/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TicketServiceName is the fully-qualified name of the TicketService service.
	TicketServiceName = "api.TicketService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TicketServiceGetTicketProcedure is the fully-qualified name of the TicketService's GetTicket RPC.
	TicketServiceGetTicketProcedure = "/api.TicketService/GetTicket"
)

// TicketServiceClient is a client for the api.TicketService service.
type TicketServiceClient interface {
	GetTicket(context.Context, *connect.Request[api.GetTicketRequest]) (*connect.Response[api.GetTicketResponse], error)
}

// NewTicketServiceClient constructs a client for the api.TicketService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTicketServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TicketServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	ticketServiceMethods := api.File_tickets_proto.Services().ByName("TicketService").Methods()
	return &ticketServiceClient{
		getTicket: connect.NewClient[api.GetTicketRequest, api.GetTicketResponse](
			httpClient,
			baseURL+TicketServiceGetTicketProcedure,
			connect.WithSchema(ticketServiceMethods.ByName("GetTicket")),
			connect.WithClientOptions(opts...),
		),
	}
}

// ticketServiceClient implements TicketServiceClient.
type ticketServiceClient struct {
	getTicket *connect.Client[api.GetTicketRequest, api.GetTicketResponse]
}

// GetTicket calls api.TicketService.GetTicket.
func (c *ticketServiceClient) GetTicket(ctx context.Context, req *connect.Request[api.GetTicketRequest]) (*connect.Response[api.GetTicketResponse], error) {
	return c.getTicket.CallUnary(ctx, req)
}

// TicketServiceHandler is an implementation of the api.TicketService service.
type TicketServiceHandler interface {
	GetTicket(context.Context, *connect.Request[api.GetTicketRequest]) (*connect.Response[api.GetTicketResponse], error)
}

// NewTicketServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTicketServiceHandler(svc TicketServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ticketServiceMethods := api.File_tickets_proto.Services().ByName("TicketService").Methods()
	ticketServiceGetTicketHandler := connect.NewUnaryHandler(
		TicketServiceGetTicketProcedure,
		svc.GetTicket,
		connect.WithSchema(ticketServiceMethods.ByName("GetTicket")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.TicketService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TicketServiceGetTicketProcedure:
			ticketServiceGetTicketHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTicketServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTicketServiceHandler struct{}

func (UnimplementedTicketServiceHandler) GetTicket(context.Context, *connect.Request[api.GetTicketRequest]) (*connect.Response[api.GetTicketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.TicketService.GetTicket is not implemented"))
}
