// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: venue.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/alecsavvy/shreddr/server/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// VenueServiceName is the fully-qualified name of the VenueService service.
	VenueServiceName = "api.VenueService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VenueServiceGetVenueProcedure is the fully-qualified name of the VenueService's GetVenue RPC.
	VenueServiceGetVenueProcedure = "/api.VenueService/GetVenue"
	// VenueServiceListVenuesProcedure is the fully-qualified name of the VenueService's ListVenues RPC.
	VenueServiceListVenuesProcedure = "/api.VenueService/ListVenues"
	// VenueServiceCreateVenueProcedure is the fully-qualified name of the VenueService's CreateVenue
	// RPC.
	VenueServiceCreateVenueProcedure = "/api.VenueService/CreateVenue"
)

// VenueServiceClient is a client for the api.VenueService service.
type VenueServiceClient interface {
	GetVenue(context.Context, *connect.Request[api.GetVenueRequest]) (*connect.Response[api.GetVenueResponse], error)
	ListVenues(context.Context, *connect.Request[api.ListVenuesRequest]) (*connect.Response[api.ListVenuesResponse], error)
	CreateVenue(context.Context, *connect.Request[api.CreateVenueRequest]) (*connect.Response[api.CreateVenueResponse], error)
}

// NewVenueServiceClient constructs a client for the api.VenueService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVenueServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) VenueServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	venueServiceMethods := api.File_venue_proto.Services().ByName("VenueService").Methods()
	return &venueServiceClient{
		getVenue: connect.NewClient[api.GetVenueRequest, api.GetVenueResponse](
			httpClient,
			baseURL+VenueServiceGetVenueProcedure,
			connect.WithSchema(venueServiceMethods.ByName("GetVenue")),
			connect.WithClientOptions(opts...),
		),
		listVenues: connect.NewClient[api.ListVenuesRequest, api.ListVenuesResponse](
			httpClient,
			baseURL+VenueServiceListVenuesProcedure,
			connect.WithSchema(venueServiceMethods.ByName("ListVenues")),
			connect.WithClientOptions(opts...),
		),
		createVenue: connect.NewClient[api.CreateVenueRequest, api.CreateVenueResponse](
			httpClient,
			baseURL+VenueServiceCreateVenueProcedure,
			connect.WithSchema(venueServiceMethods.ByName("CreateVenue")),
			connect.WithClientOptions(opts...),
		),
	}
}

// venueServiceClient implements VenueServiceClient.
type venueServiceClient struct {
	getVenue    *connect.Client[api.GetVenueRequest, api.GetVenueResponse]
	listVenues  *connect.Client[api.ListVenuesRequest, api.ListVenuesResponse]
	createVenue *connect.Client[api.CreateVenueRequest, api.CreateVenueResponse]
}

// GetVenue calls api.VenueService.GetVenue.
func (c *venueServiceClient) GetVenue(ctx context.Context, req *connect.Request[api.GetVenueRequest]) (*connect.Response[api.GetVenueResponse], error) {
	return c.getVenue.CallUnary(ctx, req)
}

// ListVenues calls api.VenueService.ListVenues.
func (c *venueServiceClient) ListVenues(ctx context.Context, req *connect.Request[api.ListVenuesRequest]) (*connect.Response[api.ListVenuesResponse], error) {
	return c.listVenues.CallUnary(ctx, req)
}

// CreateVenue calls api.VenueService.CreateVenue.
func (c *venueServiceClient) CreateVenue(ctx context.Context, req *connect.Request[api.CreateVenueRequest]) (*connect.Response[api.CreateVenueResponse], error) {
	return c.createVenue.CallUnary(ctx, req)
}

// VenueServiceHandler is an implementation of the api.VenueService service.
type VenueServiceHandler interface {
	GetVenue(context.Context, *connect.Request[api.GetVenueRequest]) (*connect.Response[api.GetVenueResponse], error)
	ListVenues(context.Context, *connect.Request[api.ListVenuesRequest]) (*connect.Response[api.ListVenuesResponse], error)
	CreateVenue(context.Context, *connect.Request[api.CreateVenueRequest]) (*connect.Response[api.CreateVenueResponse], error)
}

// NewVenueServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVenueServiceHandler(svc VenueServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	venueServiceMethods := api.File_venue_proto.Services().ByName("VenueService").Methods()
	venueServiceGetVenueHandler := connect.NewUnaryHandler(
		VenueServiceGetVenueProcedure,
		svc.GetVenue,
		connect.WithSchema(venueServiceMethods.ByName("GetVenue")),
		connect.WithHandlerOptions(opts...),
	)
	venueServiceListVenuesHandler := connect.NewUnaryHandler(
		VenueServiceListVenuesProcedure,
		svc.ListVenues,
		connect.WithSchema(venueServiceMethods.ByName("ListVenues")),
		connect.WithHandlerOptions(opts...),
	)
	venueServiceCreateVenueHandler := connect.NewUnaryHandler(
		VenueServiceCreateVenueProcedure,
		svc.CreateVenue,
		connect.WithSchema(venueServiceMethods.ByName("CreateVenue")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.VenueService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VenueServiceGetVenueProcedure:
			venueServiceGetVenueHandler.ServeHTTP(w, r)
		case VenueServiceListVenuesProcedure:
			venueServiceListVenuesHandler.ServeHTTP(w, r)
		case VenueServiceCreateVenueProcedure:
			venueServiceCreateVenueHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVenueServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedVenueServiceHandler struct{}

func (UnimplementedVenueServiceHandler) GetVenue(context.Context, *connect.Request[api.GetVenueRequest]) (*connect.Response[api.GetVenueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.VenueService.GetVenue is not implemented"))
}

func (UnimplementedVenueServiceHandler) ListVenues(context.Context, *connect.Request[api.ListVenuesRequest]) (*connect.Response[api.ListVenuesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.VenueService.ListVenues is not implemented"))
}

func (UnimplementedVenueServiceHandler) CreateVenue(context.Context, *connect.Request[api.CreateVenueRequest]) (*connect.Response[api.CreateVenueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.VenueService.CreateVenue is not implemented"))
}
