// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID             int32
	Name           string
	Description    string
	Date           pgtype.Timestamp
	Location       interface{}
	CreatorAddress string
	PriceCents     int64
	ImageUrl       string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type User struct {
	ID            int32
	WalletAddress string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
