// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Date        pgtype.Timestamp `json:"date"`
	VenueID     string           `json:"venue_id"`
	PriceCents  int64            `json:"price_cents"`
	ImageUrl    string           `json:"image_url"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	PublicKey string           `json:"public_key"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Venue struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Latitude    float64          `json:"latitude"`
	Longitude   float64          `json:"longitude"`
	Country     string           `json:"country"`
	Region      string           `json:"region"`
	City        string           `json:"city"`
	Capacity    int32            `json:"capacity"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
