// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetEvent(ctx context.Context, id string) (*Event, error)
	GetUser(ctx context.Context, publicKey string) (*User, error)
	GetVenue(ctx context.Context, id string) (*Venue, error)
	InsertEvent(ctx context.Context, arg *InsertEventParams) (*Event, error)
	InsertUser(ctx context.Context, publicKey string) (*User, error)
	InsertVenue(ctx context.Context, arg *InsertVenueParams) (*Venue, error)
	ListEvents(ctx context.Context) ([]*Event, error)
	ListVenues(ctx context.Context) ([]*Venue, error)
}

var _ Querier = (*Queries)(nil)
