// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reads.sql

package db

import (
	"context"
)

const getEvent = `-- name: GetEvent :one
select id, name, description, date, location, creator_address, price_cents, image_url, created_at, updated_at from events where id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int32) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Date,
		&i.Location,
		&i.CreatorAddress,
		&i.PriceCents,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByWallet = `-- name: GetUserByWallet :one
select id, wallet_address, created_at, updated_at from users where wallet_address = $1
`

func (q *Queries) GetUserByWallet(ctx context.Context, walletAddress string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWallet, walletAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
select id, name, description, date, location, creator_address, price_cents, image_url, created_at, updated_at from events
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Date,
			&i.Location,
			&i.CreatorAddress,
			&i.PriceCents,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
