// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: writes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :one
insert into events (id, name, description, date, location, creator_address, price_cents, image_url) values ($1, $2, $3, $4, $5, $6, $7, $8) returning id, name, description, date, location, creator_address, price_cents, image_url, created_at, updated_at
`

type InsertEventParams struct {
	ID             int32
	Name           string
	Description    string
	Date           pgtype.Timestamp
	Location       interface{}
	CreatorAddress string
	PriceCents     int64
	ImageUrl       string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Date,
		arg.Location,
		arg.CreatorAddress,
		arg.PriceCents,
		arg.ImageUrl,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Date,
		&i.Location,
		&i.CreatorAddress,
		&i.PriceCents,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
insert into users (id, wallet_address) values ($1, $2) returning id, wallet_address, created_at, updated_at
`

type InsertUserParams struct {
	ID            int32
	WalletAddress string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.ID, arg.WalletAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
