// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: writes.sql

package db

import (
	"context"
	"time"
)

const deleteEvent = `-- name: DeleteEvent :exec
update events set deleted_at = now() where id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
update users set deleted_at = now() where public_key = $1
`

func (q *Queries) DeleteUser(ctx context.Context, publicKey string) error {
	_, err := q.db.Exec(ctx, deleteUser, publicKey)
	return err
}

const deleteVenue = `-- name: DeleteVenue :exec
update venues set deleted_at = now() where id = $1
`

func (q *Queries) DeleteVenue(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteVenue, id)
	return err
}

const insertEvent = `-- name: InsertEvent :one
insert into events (id, name, description, date, venue_id, price_cents, image_url) values ($1, $2, $3, $4, $5, $6, $7) returning id, name, description, date, venue_id, price_cents, image_url, created_at, updated_at, deleted_at
`

type InsertEventParams struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Date        time.Time `json:"date"`
	VenueID     string    `json:"venue_id"`
	PriceCents  int64     `json:"price_cents"`
	ImageUrl    string    `json:"image_url"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg *InsertEventParams) (*Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Date,
		arg.VenueID,
		arg.PriceCents,
		arg.ImageUrl,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Date,
		&i.VenueID,
		&i.PriceCents,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const insertUser = `-- name: InsertUser :one
insert into users (public_key) values ($1) on conflict (public_key) do nothing returning public_key, created_at, updated_at, deleted_at
`

func (q *Queries) InsertUser(ctx context.Context, publicKey string) (*User, error) {
	row := q.db.QueryRow(ctx, insertUser, publicKey)
	var i User
	err := row.Scan(
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const insertVenue = `-- name: InsertVenue :one
insert into venues (id, name, description, latitude, longitude, country, region, city, capacity) values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning id, name, description, latitude, longitude, country, region, city, capacity, created_at, updated_at, deleted_at
`

type InsertVenueParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
	Country     string  `json:"country"`
	Region      string  `json:"region"`
	City        string  `json:"city"`
	Capacity    int32   `json:"capacity"`
}

func (q *Queries) InsertVenue(ctx context.Context, arg *InsertVenueParams) (*Venue, error) {
	row := q.db.QueryRow(ctx, insertVenue,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
		arg.Country,
		arg.Region,
		arg.City,
		arg.Capacity,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.Country,
		&i.Region,
		&i.City,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
